_localStrings = {
    ACTIONS: 'Actions',
    ACTIONS_DESC: 'Print, Attach File, Archive, Send to Self',
    ADD_COMMENT: 'Add Comment',
    ADD_FOLDERS: 'Add Folder(s)',
    ADD_TAG: 'Add Tag',
    ADD_TAGS: 'Add Tag(s)',
    ADD_USERS_EMAILS: 'Add Users/Emails',
	ADDITIONAL: 'Additional',
    ALL_NOTES: 'Unfiled',
    ATTACHMENTS: 'Attachments: ',
    ATTACH_FILE: 'Attach File',
    ATTACH_REMOVE_CONFIRM: 'Are you sure you want to remove this attachment?',
    APPLY: 'Update',
    BACK: 'Back to ',
    BOOKMARKS: 'Bookmarks',
    BROWSE_AWAY: 'Are you sure you want to leave Ubernote?',
    CANCEL: 'Cancel',
    CLICK_TO_EDIT_TITLE: 'Click to Edit Title',
    CLOSE: 'Close',
	COMMENTS_HEADING: 'Comments:',
    CREATEDT_NEWFIRST: 'Recently Created',
    CREATEDT_OLDFIRST: 'Oldest Created',
    CREATE_DATE: 'Attached on: ',
    CREATE_DATE_HEADER: 'Created: ',
    CURRENT_CATEGORY: 'Viewing: ',
    DASHBOARD: 'Dashboard',
    DATA_FIELD_NOT_FOUND: 'Data Field Not Found',
    DELETE: 'Delete',
    DELETED_NOTE_POPUP_CLOSE: 'The note you are editing has been deleted, this window will be closed.',
    DELETED_NOTE_PREVIOUS_PAGE: 'The note you are editing has been deleted, you will be redirected to the previous page.',
    DELETE_CONFIRM: 'Are you sure you want to permanently delete the note: ',
    DELETE_NOTES_CONFIRM: 'Are you sure you want to permanently delete the selected notes ',
    DELETE_NOTE: 'Delete Note',
    DELETE_TAG: 'Delete Tag',
    DOWNLOAD: 'Download',
    DUPLICATE_TAG_NAMES_ADD: 'The following are duplicate tag names and have not been added: ',
    DUPLICATE_TAG_NAMES_RENAME: 'Another tag already exists with the name: ',
    EDITED: 'Edited',
    EMAIL_SHARE_NOTE: 'Email/Share Note',
    EMAIL_TO_SELF: 'Email to self',
    EMPTY: '[Empty]',
    EMPTY_SEARCH_TERM_ERROR: 'Search term cannot be empty',
    EMPTY_TITLE_CONFIRM: 'No Title - Click To Edit',
    EMPTY_TRASH_CONFIRM: 'Are you sure you want to empty the trash?',
    EMPTY_VIEWNODE_NAME_ERROR: 'Tag name cannot be empty',
    ENTER_NAME: 'Please enter the name of the tag you wish to create',
    EXTENSION: 'Extension: ',
    EXTERNAL: 'New Window',
    EXTERNAL_ADD: 'External note addition',
    EXTERNAL_MODIFY: 'External note modification',
    EXPANDED: 'Expanded',
    FILE_NAME: 'Name: ',
    GOTO_PAGE: 'Go To Page ',
    HELP: 'Help',
    HI: 'Hi, ',
    HIDDEN: 'Archive',
    HIDE: 'Archive',
    HISTORY: 'History',
    IMPORTANT: 'Important',
    IMPORTANT_STATUS: 'Important Status',
    INLINE: 'Current Window',
    INVALID_DATA_FORMAT_SPECIFIED: 'Invalid Data Format Specified',
    KB: 'KB',
    LIST: 'List',
    LOADING: 'Loading...',
    LOGOUT: 'Log Out',
    MARK_HIDDEN: 'Archive',
    MARK_IMPORTANT: 'Mark Important',
    MARK_PUBLIC: 'Mark Public',
    MARK_PRIVATE: 'Mark Private',
    MAXIMIZE: 'Expand',
	ME: 'Me',
    MINIMIZE: 'Collapse',
	MINIMIZE_COMMENTS: 'Minimize List',
    MODIFIED_DATE_HEADER: 'Modified: ',
    MORE: 'More',
	MOVE: 'Move',
    NAME: 'Name: ',
    NEW_TAG: '(new)',
    NEW_FOLDER: '(new)',
    NEW_NOTE: 'New Note',
    NEW_TAGS: 'New Tag(s)',
    NEW_FOLDERS: 'New Folder(s)',
    NEW_WINDOW: 'New Window',
	NEXT: 'Next Page',
	NEXT_INDICATOR: '>>',
    NOTE: 'Note',
    NOTES: 'Notes',
	NOTE_FOLDERS: 'Note Folders',
    NOTE_HISTORY: 'Note History',
    NOTE_SENT: 'Note Sent',
    NOTE_SHARES: 'Note Shares',
	NOTE_TAGS: 'Note Tags',
	NOTE_UPLOADS: 'Note Uploads',
	NO_MESSAGE: 'No Message Given!',
    NO_NOTES_FOUND: 'No notes found',
    OF: 'of',
    OK: 'OK',
    OPEN_TASKS: 'Open Tasks',
    OTHERS_SHARED_WITH: 'Other People Shared With: ',
	PREVIOUS: 'Previous Page',
	PREVIOUS_INDICATOR: '<<',
    PRINT: 'Print',
    PUBLIC: 'Public',
    PUBLIC_NOTES: 'My Public Notes',
    READ: 'Read',
    REMOVE: 'Remove',
    REMOVE_TAG: 'Remove',
    RENAME: 'Rename',
    RENAME_NOTE: 'Rename Note',
    RENAME_TAG: 'Rename Tag',
    SAVED: 'Saved',
    SEARCH: 'Search',
    SEARCH_TERM: 'Results for search term: ',
    SELECT_ALL: 'All',
    SELECT_NONE: 'None',
    SELECT_OPEN: 'Open Selected',
    SEND_FEEDBACK: 'Send us feedback',
    SETTINGS: 'Settings and Tools',
    SHARE: 'Share',
	SHARED: 'Shared',
    SHARE_ERROR_NOT_OWNER: 'Notes created by other users cannot be shared, not all notes have been shared.',
    SHARED_BY: 'Owner: ',
    SHARED_WITH: 'Shared With: ',
    SHARE_LEVEL: 'Share Level: ',
    SHARING: 'Sharing',
    SHOW_SELECTED: 'Expand Selected',
	SHOW_ALL_COMMENTS: 'Expand Full List',
    SINGLENOTE: 'Single Note',
    SIZE: 'Size: ',
    SORT_ORDER: 'By:',
    TAG: 'Tag',
    TAG_MENU: 'Add/Remove Tags from Note',
	TAGGED: 'Tagged',
    TAGS: 'Tags: ',
    TITLE_ATOZ: 'Title A-Z',
    TITLE_POSTFIX: ' - UberNote',
    TITLE_PREFIX: '',
    TITLE_ZTOA: 'Title Z-A',
    TOOLTIP_CLICK_CHANGE_ORDER: 'Click to change note display order',
    TOOLTIP_PAGE_TEXT: 'Select page ',
    TRASH: 'Trash',
    TRASH_CONFIRM: 'Are you sure you want to trash the note: ',
    TRASH_NOTE: 'Trash Note',
    TRASH_NOTE_POPUP_CLOSE: 'The note you are editing has been trashed, this window will be closed.',
    TRASH_NOTES_CONFIRM: 'Are you sure you want to trash the selected notes?',
    UNDEFINED: 'Undefined',
    UNHIDE: 'Unarchive',
    UNMARK_HIDDEN: 'Unarchive',
    UNMARK_IMPORTANT: 'Unmark Important',
    UNTAGGED: 'Untagged',
    UNTITLED: 'Untitled',
    UNTRASH: 'Untrash',
    UNTRASH_NOTE: 'Untrash Note',
    UPDATEDT_NEWFIRST: 'Recently Modified',
    UPDATEDT_OLDFIRST: 'Oldest Modified',
    UPDATE_DATE: 'Updated on: ',
    UPDATE_USER: 'Last Updated By: ',
    VIEW: 'View',
    VIEWING_SELECTED_NOTE: 'Viewing: <b>Selected Note</b>',
    VIEWING_SELECTED_NOTES: 'Viewing: <b>Selected Notes</b>',
    WRITE: 'Write',
    all: 'All Notes',
    bookmarked: 'Bookmarks',
    hidden: 'Archive',
    'public': 'Public',
    search: 'Search',
    starred: 'Important',
    trashed: 'Trashed',
    unchecked: 'Open Tasks',
    untagged: 'Untagged',
	my: 'My Notes'
};
